wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.13
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.9
    t:
      1:
      - 2
      - 3
      - 5
      4: 3.7.9
      5: 0.10.13
      8:
      - 1
activation:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 100
epochs:
  desc: null
  value: 150
learning_rate:
  desc: null
  value: 0.0001
optimizer:
  desc: null
  value: adam
