wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.13
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.9
    t:
      1:
      - 3
      - 5
      - 7
      - 8
      2:
      - 3
      - 5
      - 7
      - 8
      3:
      - 2
      4: 3.7.9
      5: 0.10.13
      8:
      - 1
learning_rate:
  desc: null
  value: 0.05
metric:
  desc: null
  value: auc
n_estimators:
  desc: null
  value: 200
num_leaves:
  desc: null
  value: 30
objective:
  desc: null
  value: binary
scale_pos_weight:
  desc: null
  value: 2
